export const projects = {
  webflow: [
    {
      id: 1,
      title: "Biggerstaff Construction",
      description:
        "A clean, modern website for a luxury home builder, showcasing their collection of high-end homes. Utilized Webflow CMS for optimal user experience in browsing listed properties.",
      imageSrc: "/images/biggerstaff.png",
      projectUrl: "https://www.biggerstaffconstruction.com/",
      type: "webflow",
      features: [
        "Responsive design optimized for all devices",
        "Webflow CMS integration for easy content management",
        "Custom property listing functionality with filtering options",
        "High-quality image galleries for each property",
        "Seamless integration of contact forms for inquiries",
      ],
      technologies: [
        "Webflow",
        "Webflow CMS",
        "JavaScript",
        "CSS3",
        "HTML5",
        "Responsive Design",
      ],
    },
    {
      id: 2,
      title: "Bright Realty",
      description:
        "Developed for a marketing agency with provided design. Implemented custom code for dynamic effects, including an eye-catching home page slider hero.",
      imageSrc: "/images/brightrealty.png",
      projectUrl: "https://www.brightrealty.com/",
      type: "webflow",
      features: [
        "Custom-coded homepage slider with smooth transitions",
        "Integration with client's existing CRM systems",
        "Optimized for fast loading speeds and performance",
        "Mobile-first approach ensuring seamless experience across all devices",
        "Advanced search functionality for property listings",
      ],
      technologies: [
        "Webflow",
        "JavaScript",
        "CSS3",
        "HTML5",
        "API Integration",
        "CRM Integration",
      ],
    },
    {
      id: 3,
      title: "One West Village",
      description:
        "An innovative side-scrolling website showcasing a new office building. Coordinated custom video production to enhance the visual experience.",
      imageSrc: "/images/onewestvillage.png",
      projectUrl: "https://www.onewestvillage.com",
      type: "webflow",
      features: [
        "Innovative side-scrolling design for unique user experience",
        "Custom video integration showcasing the office building",
        "Interactive floor plans and space availability features",
        "Smooth scrolling animations and transitions",
        "Integrated booking system for office space tours",
      ],
      technologies: [
        "Webflow",
        "JavaScript",
        "CSS3",
        "HTML5",
        "Video Integration",
        "Custom Animations",
      ],
    },
    {
      id: 4,
      title: "Texas Branding Station",
      description:
        "A fresh website for a Texas-themed branding experience, featuring videos and images to showcase products. Includes region-specific pricing details.",
      imageSrc: "/images/tbs.png",
      projectUrl: "https://www.texasbrandingstation.com/",
      type: "webflow",
      features: [
        "Dynamic content showcasing various branding experiences",
        "Region-specific pricing implementation",
        "Custom video player integration for product demonstrations",
        "Interactive Hat Bar configurator",
        "Event calendar and booking system for traveling experiences",
      ],
      technologies: [
        "Webflow",
        "JavaScript",
        "CSS3",
        "HTML5",
        "Video Integration",
        "Interactive Features",
      ],
    },
  ],
  other: [
    {
      id: 5,
      title: "Weller Capital",
      description:
        "WordPress website developed in collaboration with a marketing agency. Integrated dynamic movement throughout the site while maintaining excellent user experience.",
      imageSrc: "/images/WellerCapital.png",
      projectUrl: "https://jwellercapital.com/",
      type: "wordpress",
      features: [
        "Custom WordPress theme development",
        "Advanced animations and transitions",
        "Integration with financial data APIs",
        "Secure client portal implementation",
        "Mobile-responsive design with custom breakpoints",
      ],
      technologies: [
        "WordPress",
        "PHP",
        "JavaScript",
        "CSS3",
        "HTML5",
        "MySQL",
        "API Integration",
      ],
    },
    {
      id: 6,
      title: "Maven Lighting",
      description:
        "Developed a WordPress website from scratch for Maven Lighting. The client wanted to showcase their wide range of completed projects with a professional look aligned with their branding.",
      imageSrc: "/images/MavenLighting.png",
      projectUrl: "https://mavenlighting.com/",
      type: "wordpress",
      features: [
        "Custom WordPress theme tailored to client's brand identity",
        "Portfolio showcase with filterable categories",
        "Integration of a quote request system",
        "Optimized image galleries for fast loading",
        "Blog section for sharing industry insights and project updates",
      ],
      technologies: [
        "WordPress",
        "PHP",
        "JavaScript",
        "CSS3",
        "HTML5",
        "MySQL",
        "WooCommerce",
      ],
    },
  ],
};
